# Generated by Django 5.0.4 on 2024-04-11 23:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0003_refeicao_opcao'),
    ]

    operations = [
        migrations.AddField(
            model_name='refeicao',
            name='paciente',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='plataforma.pacientes'),
            preserve_default=False,
        ),
    ]
